### PR TITLE
aya-log: Move the `Pod` implementations from aya-log-common to aya-log

### PR DESCRIPTION
**Pull request by vadorovsky**
Keeping the `Pod` implementations and optional dependency on aya in aya-log-common breaks the clippy checks (which are made on the entire workspace).

The reason is that when different crates inside the workspace have the same dependency with different features, that dependency is built only once with the sum of features needed by all crates. It's **not** being built separately with different feature sets.

That's why, before this change, aya-log-common was built once for the entire workspace with `userspace` feature enabled. That made importing aya-log-ebpf inside integration-ebpf impossible. The aya-log-common build, with `userspace` feature enabled, was pulling std as a dependency. Therefore, importing aya-log-ebpf inside integration-ebpf resulted in including std and errors like:

```
error[E0152]: found duplicate lang item `panic_impl`
  --> test/integration-ebpf/src/log.rs:23:1
   |
23 | fn panic(_info: &core::panic::PanicInfo) -> ! {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: the lang item is first defined in crate `std` (which `aya` depends on)
```

This change fixes the problem by removing the `userspace` feature from aya-log-common and moving the `Pod` implementations to aya-log.

### CODE REVIEW

File: aya-log/src/lib.rs [hunk 1]
```diff
@@ -73,6 +73,17 @@ use aya::{
     Bpf, Pod,
 };
 
+#[derive(Copy, Clone)]
+struct RecordField(aya_log_common::RecordField);
```
[the remark this answers is not in the document]
Comment (alessandrod) [reply aya-log/src/lib.rs:77]: Also, wouldn't it better to name these RecordFieldWrapper ArgumentWrapper and DisplayHintWrapper so that we don't have the name clash and don't have to use the aya_log_common:: prefix everywhere else?

[the remark this answers is not in the document]
Comment (vadorovsky) [reply aya-log/src/lib.rs]: Done, thanks
